"""Single-file HTML renderer for an incident brief — judge-ready visual output."""
import html


_CSS = """
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
  background: #0f1115;
  color: #e6e8eb;
  padding: 32px 16px;
  line-height: 1.5;
}
.container { max-width: 880px; margin: 0 auto; }
header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding-bottom: 20px;
  border-bottom: 1px solid #1f2430;
  margin-bottom: 24px;
}
h1 { font-size: 20px; font-weight: 600; letter-spacing: -0.01em; }
.subtitle { font-size: 13px; color: #8b93a7; margin-top: 4px; }
.badge {
  display: inline-block;
  padding: 6px 12px;
  border-radius: 999px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: 0.03em;
  text-transform: uppercase;
}
.badge.approval_required {
  background: #3a1b1b;
  color: #ff9b9b;
  border: 1px solid #5a2323;
}
.badge.allowed {
  background: #1b3a26;
  color: #8eecae;
  border: 1px solid #235a32;
}
.grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
}
.block {
  background: #151922;
  border: 1px solid #1f2430;
  border-radius: 12px;
  padding: 20px;
}
.block h2 {
  font-size: 11px;
  font-weight: 600;
  color: #8b93a7;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  margin-bottom: 10px;
}
.block .text {
  font-size: 15px;
  color: #e6e8eb;
  white-space: pre-wrap;
  margin-bottom: 14px;
}
.evidence {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
.tag {
  display: inline-block;
  padding: 3px 8px;
  background: #0f1115;
  border: 1px solid #2a3040;
  border-radius: 4px;
  font-size: 11px;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  color: #8b93a7;
}
.tag.rca { color: #9ecdff; border-color: #2a3a5a; }
.tag.score { color: #ffcf8e; border-color: #5a4328; }
footer {
  margin-top: 24px;
  padding-top: 16px;
  border-top: 1px solid #1f2430;
  font-size: 11px;
  color: #5a6275;
  text-align: center;
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
}
@media (max-width: 640px) { .grid { grid-template-columns: 1fr; } }
"""


def _tag_class(ref: str) -> str:
    if ref.startswith("rca:"):
        return "tag rca"
    if ref.startswith("score:"):
        return "tag score"
    return "tag"


def _render_block(title: str, block: dict) -> str:
    if not isinstance(block, dict):
        block = {}
    text = html.escape(str(block.get("text", "")))
    refs = block.get("evidence_refs") or []
    evidence_html = "".join(
        f'<span class="{_tag_class(r)}">{html.escape(str(r))}</span>'
        for r in refs
    )
    return (
        f'<div class="block">'
        f'<h2>{html.escape(title)}</h2>'
        f'<div class="text">{text}</div>'
        f'<div class="evidence">{evidence_html}</div>'
        f'</div>'
    )


def render_brief_html(brief: dict) -> str:
    incident_id = html.escape(str(brief.get("incident_id", "unknown")))
    policy = str(brief.get("policy_state", "allowed"))
    policy_class = "approval_required" if policy == "approval_required" else "allowed"

    blocks = (
        _render_block("What failed", brief.get("what_failed", {}))
        + _render_block("What is impacted", brief.get("what_is_impacted", {}))
        + _render_block("Who acts first", brief.get("who_acts_first", {}))
        + _render_block("What to do next", brief.get("what_to_do_next", {}))
    )

    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Incident Brief — {incident_id}</title>
<style>{_CSS}</style>
</head>
<body>
<div class="container">
  <header>
    <div>
      <h1>Incident {incident_id}</h1>
      <div class="subtitle">OpenMetadata DQ Copilot · evidence-backed triage brief</div>
    </div>
    <span class="badge {policy_class}">{html.escape(policy)}</span>
  </header>
  <div class="grid">
    {blocks}
  </div>
  <footer>Generated by metadata-incident-copilot · deterministic · reproducible</footer>
</div>
</body>
</html>
"""
